---

- hosts: all
  become: true
  tasks:

    - name: update and install apache2 and php packages for CentOs
      package:
        name: 
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
        update_cache: yes
        when: ansible_distribution == "CentOs"

    - name: update and install apache2 and php packages for CentOs
      package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
        update_cache: yes
        when: ansible_distribution == "Ubuntu"
